create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  qty integer not null default 0,
  price numeric not null default 0,
  created_at timestamp with time zone default now()
);

create table if not exists transactions (
  id bigint generated by default as identity primary key,
  type text not null,
  description text not null,
  amount numeric not null default 0,
  created_at timestamp with time zone default now()
);
